version: '3.8'

services:
 backend:
    image: chatbot-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_API_KEY=${AZURE_INFERENCE_CREDENTIAL}
      - MODEL_NAME=${MODEL_NAME}
    env_file:
       - ./backend/.env
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3